version: 2.1
jobs:
  build:
    working_directory: ~/CircleCi
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKER_HUB_USER_ID
          password: $DOCKER_HUB_PWD
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # - run:
      #     name: Run tests
      #     command: |
      #       docker-compose -f ./docker-compose.test.yml up
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKER_HUB_USER_ID/nginx-app-marian:latest .
      - run:
          name: Push application Docker image
          command: |
            TAG=latest
            echo $DOCKER_HUB_PWD | docker login -u $DOCKER_HUB_USER_ID --password-stdin
            docker push $DOCKER_HUB_USER_ID/nginx-app-marian:$TAG