version: 2.1
jobs:
  build:
    working_directory: /CircleCi
    docker:
      - image: docker:20.10.16
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependecies
          command: |
            apk add --no-cache python3 py3-pip
            pip3 install docker-compose