version: 2.1
jobs:
  build:
    working_directory: /CircleCi
    docker:
      - image: docker:20.10.16
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependecies
          command: |
            apk add --no-cache python3 py3-pip
            pip install --upgrade setuptools wheel
            pip install Cython
            sudo apt-get install build-essential
            pip3 install docker-compose
      - deploy:
          name: Push application Docker Image
          command: |
            docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USER_ID -p $DOCKERHUB_HUB_PWD
            docker build -t mariancap/nginx-circleci:latest .
            docker push mariancap/nginx-circleci:latest